### ISSUE TITLE
Finalize mesh account model

### ISSUE THREAD

**Issue by avive** [spacemeshos/research#3]
@avive:
We need to decide if we are going with a unified account abstraction that covers both simple coin accounts and smart contract accounts or 2 type of accounts in the db: smart contract instances and coin balance accounts.

@lrettig 
Some more context on this question: https://docs.google.com/document/d/1rUDWsx4nKcGmtRFOSy3MKT5FpcIUdSIQFVbyqWGcnUo/edit?disco=AAAADf0puIg

I personally feel (and I believe that Vitalik and others feel) that having multiple account types in Ethereum was a mistake, and overcomplicated. Ethereum for a long time has wanted to move to a single account type (it's referred to as "account abstraction") and I believe this is in the roadmap for eth2 but I don't think eth1 will ever get there.

It basically means that all addresses are contracts, and, in the simplest case, a contract may specify a simple ECDSA signature verification and allow funds to be moved, emulating an existing Ethereum key-based "EOA" (externally owned account).

I suspect we're very likely to be stuck in the same situation as Ethereum if we don't have a VM ready for the first mainnet release and therefore need some sort of "EOA" type simple account to begin with.

@avive: 
We need to discuss the cons - memory storage for contract based accounts e.g. smart wallets. We decided to have smart wallet instances in 0.3.5 but it might be too expensive to handle each coin transfer tx as a smart contract method call...

**Comment by avive** [comment]
Our current proposal is a simple account model for user balances and nonces and a smart-contract account with additional smart-contract specific meta-data such as code-template and complex state. @YaronWittenstein @lrettig

**Comment by lrettig** [comment]
> memory storage for contract based accounts e.g. smart wallets

This can be avoided using stateless clients (which is admittedly a whole different can of worms).

> it might be too expensive to handle each coin transfer tx as a smart contract method call

Expensive how?

> Our current proposal is a simple account model for user balances and nonces and a smart-contract account with additional smart-contract specific meta-data such as code-template and complex state.

Right, this sounds exactly like Ethereum--which means we know it works, but my point above stands.

**Comment by avive** [comment]
- We are not going to have stateless clients for 0.2 so it is not a viable solution.
- Expensive to execute a smart contract transaction instead of a native coin transaction in terms memory allocations and cpu work.
- Further discussion needed.

**Comment by lrettig** [comment]
> We are not going to have stateless clients for 0.2 so it is not a viable solution.

I'm not disagreeing, I just want to understand the logic behind the decision--is it because we think it's harder to engineer this?

> Expensive to execute a smart contract transaction instead of a native coin transaction in terms memory allocations and cpu work.

This seems like an "inside-the-VM" vs. "outside-the-VM" question. If so, yes, it's obviously cheaper to do outside the VM. But there are potential optimizations/shortcuts such as VM opcodes calling into native host functions that incur minimal additional overhead. (EC math is another area where we'd want to explore doing something like this.)

**Comment by lrettig** [comment]
We decided to go with account abstraction/unification, see https://github.com/spacemeshos/pm/issues/3.
